# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 极客猴
description: >- #
  猴哥的个人博客: 极客猴。分享自己总结的Python爬虫，Web开发，数据分析的心得。
  此外还输出自己的思考内容，涉猎产品知识、个人成长等，每周给你带来头脑大爆炸。
baseurl: ""
url: "https://monkey-soft.github.io"
repository: monkey-soft
# 文章链接格式
permalink: /:short_year:i_month:i_day.html
# permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: /page:num


# 个人信息配置
github_profile: "https://github.com/monkey-soft"
user: "猴哥"
user_email: "chanql123@163.com"
#contact_url: "https://goo.gl/tVljbV"

# 统计
# Analytics settings
google_tracking_id: "UA-49128543-2"
google_site_verification: "UA-49128543-2"

# 评论系统
#disqus_shortname: ""

# Gems
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true